app/tax/forms.py
# coding:utf-8

from flask_wtf import FlaskForm
from wtforms import SelectField, StringField, TextAreaField, SubmitField, \
    PasswordField, SelectMultipleField, FieldList
from wtforms.validators import DataRequired, Length, Email, EqualTo




class TaxForm(FlaskForm):
    envs = StringField(u'环境', validators=[DataRequired()])
    description = TextAreaField(u'环境说明')

app/tax/__init__.py
from flask import Blueprint


tax = Blueprint('tax', __name__)


from . import views

app/tax/views.py
# coding:utf-8
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

from flask import render_template, request, redirect, url_for, flash, jsonify
from . import tax
import re

@tax.route('/commercial_loan', methods=['GET', 'POST'])
def commercial_loan():
    return render_template('tax/commercial_loan.html')


@tax.route('/provident_fund_loan', methods=['GET', 'POST'])
def provident_fund_loan():
    return render_template('tax/provident_fund_loan.html')


@tax.route('/combination_loan', methods=['GET', 'POST'])
def combination_loan():
    return render_template('tax/combination_loan.html')


@tax.route('/commercial_calc', methods=['GET', 'POST'])
def commercial_calc():
    loan_total = request.form.get('loan_total')
    loan_year = request.form.get('loan_year')
    annual_rate_percent = request.form.get('loan_rate')

    loan_year = int(loan_year)
    annual_rate_percent = float(annual_rate_percent)
    loan_total = float(loan_total)
    loan_total = loan_total * 10000

    # loan_year = int(re.sub("\D", "", loan_year))
    # 还款月数
    loan_month = loan_year * 12

    # 年利率
    # annual_rate_list = re.findall(r"\((.*)\%\)", annual_rate)
    annual_rate = annual_rate_percent / 100

    # 月利率
    monthly_rate = annual_rate / 12

    average_interest_list = equal_interest(loan_month, loan_total, monthly_rate)
    average_capital_list = equal_principal(loan_month, loan_total, monthly_rate)

    debj_dict = debj_list(loan_total, monthly_rate, loan_month, annual_rate_percent)
    debx_dict = debx_list(loan_total, monthly_rate, loan_month, annual_rate_percent)

    return render_template('tax/loan_result.html', average_capital_list=average_capital_list, \
                           average_interest_list=average_interest_list, debx_dict=debx_dict, debj_dict=debj_dict)


def debj_list(loan_total, monthly_rate, loan_month, annual_rate_percent):
    # 等额本金
    debj_first_month = loan_total / loan_month + loan_total * monthly_rate
    debj_total_interest = (loan_month + 1) * loan_total * monthly_rate / 2
    debj_total = debj_total_interest + loan_total

    debj_first_month = float('%.2f' % debj_first_month)
    debj_total_interest = float('%.2f' % debj_total_interest)
    debj_total = float('%.2f' % debj_total)

    debj_dict = {'debj_first_month': debj_first_month, 'debj_total_interest': debj_total_interest,\
                 'debj_total': debj_total, 'loan_total': loan_total, 'annual_rate': annual_rate_percent}
    return debj_dict


def debx_list(loan_total, monthly_rate, loan_month, annual_rate_percent):
    # 等额本息
    debx_first_month = (loan_total * monthly_rate * (1 + monthly_rate) ** loan_month) / ((1 + monthly_rate) ** loan_month - 1)
    debx_total_interest = debx_first_month * loan_month - loan_total
    debx_total = debx_total_interest + loan_total

    debx_first_month = float('%.2f' % debx_first_month)
    debx_total_interest = float('%.2f' % debx_total_interest)
    debx_total = float('%.2f' % debx_total)

    debx_dict = {'debx_first_month': debx_first_month, 'debx_total_interest': debx_total_interest, \
                 'debx_total': debx_total, 'loan_total': loan_total, 'annual_rate': annual_rate_percent}
    return debx_dict



@tax.route('/chart_list', methods=['GET', 'POST'])
def chart_list():

    chart_list = [['Safari',    50],['Opera',     5]]
    return jsonify({
        'data': chart_list
    })

# 等额本金
# 每月还本付息金额=(本金/还款月数)+(本金-累计已还本金)×月利率
# 每月本金=总本金/还款月数
# 每月利息=(本金-累计已还本金)×月利率
# 还款总利息=（还款月数+1）*贷款额*月利率/2
# 还款总额=(还款月数+1)*贷款额*月利率/2+贷款额

def equal_principal(loan_month, loan_total, monthly_rate):
    # 每月还款本金
    monthly_principal = loan_total / loan_month

    # 还款总利息
    total_interest = (loan_month + 1) * loan_total * monthly_rate / 2

    # 还款总额
    total_repayment = total_interest + loan_total

    residual_loan = total_repayment

    i = 0
    average_capital_list = []
    while i < loan_month :
        monthly_interest = (loan_total - monthly_principal * i) * monthly_rate
        monthly_total = monthly_principal + monthly_interest
        residual_loan = residual_loan - monthly_total

        monthly_total = float('%.2f' % monthly_total)
        monthly_principal = float('%.2f' % monthly_principal)
        monthly_interest = float('%.2f' % monthly_interest)
        residual_loan = float('%.2f' % residual_loan)

        average_capital = {'monthly_total': monthly_total, 'monthly_principal': monthly_principal, 'monthly_interest': monthly_interest, 'residual_loan': residual_loan}
        average_capital_list.append(average_capital)
        i = i + 1
    return average_capital_list


# 等额本息
# 每月还本付息金额 =[ 本金*月利率*(1+月利率)贷款月数 ]/[(1+月利率)还款月数 - 1]
# 还款总利息=贷款额*贷款月数*月利率*(1+月利率)贷款月数/[(1+月利率)还款月数 - 1] -贷款额
# 还款总额=还款月数*贷款额*月利率*(1+月利率)贷款月数/[(1+月利率)还款月数 - 1]
# 每月利息 = 剩余本金*贷款月利率
# 贷款本金×月利率×〔(1+月利率)^还款月数-(1+月利率)^(还款月序号-1)〕÷〔(1+月利率)^还款月数-1〕
# 每月本金=月供-每月利息
# 每月应还本金=贷款本金×月利率×(1+月利率)^(还款月序号-1)÷〔(1+月利率)^还款月数-1〕

def equal_interest(loan_month, loan_total, monthly_rate):
    # 每月还本付息金额
    monthly_total = (loan_total * monthly_rate * (1 + monthly_rate) ** loan_month) / ((1 + monthly_rate ) ** loan_month - 1)
    #print monthly_total
    print "monthly_total = " + str(monthly_total)
    # 还款总利息
    total_interest = monthly_total * loan_month - loan_total
    print "total_interest = " + str(total_interest)

    # 还款总额
    total_repayment = total_interest + loan_total
    print "total_repayment = " + str(total_repayment)

    residual_loan = total_repayment


    i = 0
    average_interest_list = []
    while i < loan_month:
        i = i + 1
        # print "i:" + str(i)
        # 每月还款利息
        monthly_interest = loan_total * monthly_rate * ((1 + monthly_rate) ** loan_month - (1 + monthly_rate) ** (i - 1)) / ((1 + monthly_rate) ** loan_month - 1)
        # 每月还款本金
        monthly_principal = monthly_total - monthly_interest
        residual_loan = residual_loan - monthly_total

        monthly_total = float('%.2f' % monthly_total)
        monthly_principal = float('%.2f' % monthly_principal)
        monthly_interest = float('%.2f' % monthly_interest)
        residual_loan = float('%.2f' % residual_loan)

        average_interest = {'monthly_total': monthly_total, 'monthly_principal': monthly_principal,
                           'monthly_interest': monthly_interest, 'residual_loan': residual_loan}
        average_interest_list.append(average_interest)

    return average_interest_list


@tax.route('/provident_fund_clac', methods=['GET', 'POST'])
def provident_fund_clac():
    return render_template('tax/loan_result.html')


@tax.route('/combination_clac', methods=['GET', 'POST'])
def combination_clac():
    return render_template('tax/loan_result.html')





@tax.route('/purchase', methods=['GET', 'POST'])
def purchase():
    return render_template('tax/purchase.html')


@tax.route('/test4', methods=['GET', 'POST'])
def test4():
    return render_template('tax/test4.html')


@tax.route('/tax_cal', methods=['GET', 'POST'])
def tax_cal():
    buyerfirsthouse = request.form.get('buyerfirsthouse')
    selleronlyhouse = request.form.get('selleronlyhouse')
    house_total = request.form.get('house_total')
    house_org = request.form.get('house_org')
    house_area = request.form.get('house_area')
    house_year = request.form.get('house_year')
    # house_type = request.form.get('house_type')
    house_location = request.form.get('house_location')


    buyerfirsthouse = str(buyerfirsthouse)
    selleronlyhouse = str(selleronlyhouse)
    house_area = float(house_area)
    house_total = float(house_total) * 10000
    house_org = float(house_org) * 10000
    house_year = int(house_year)
    house_location = str(house_location)
    # 内环以内:0
    # 内外环之间:1
    # 外环仕外:2

    if house_area > 140:
        house_type = 'non_ordinary'
    else:
        if house_total < 4500000 and house_location == '0':
            house_type = 'ordinary'
        elif house_total < 3100000 and house_location == '1':
            house_type = 'ordinary'
        elif house_total < 2300000 and house_location == '2':
            house_type = 'ordinary'
        else:
            house_type = 'non_ordinary'

    # house_type = str(house_type)

    if buyerfirsthouse == 'on':
        buyerfirsthouse = '0'
    else:
        buyerfirsthouse = '1'

    if selleronlyhouse == 'on':
        selleronlyhouse = '0'
    else:
        selleronlyhouse = '1'

    print "buyerfirsthouse: " + str(buyerfirsthouse)
    print "selleronlyhouse: " + str(selleronlyhouse)
    print "house_area: " + str(house_area)
    print "house_total: " + str(house_total)
    print "house_org: " + str(house_org)
    print "house_year: " + str(house_year)
    print "house_type: " + str(house_type)
    print "house_location: " + str(house_location)
    # house_type:0 普通
    # buyerfirsthouse:0 买方唯一
    # selleronlyhouse:0 卖方唯一

    income_tax = personal_income_tax(house_type, house_year, house_total, house_org, selleronlyhouse)
    total_personal_income_tax = int(income_tax[0])
    margin_personal_income_tax = int(income_tax[1])
    total_vat = int(vat(house_type, house_year, house_total, house_org))
    deed_total = house_total - total_vat
    total_deed_tax = int(deed_tax(buyerfirsthouse, deed_total, house_area))

    # if total_personal_income_tax > margin_personal_income_tax:
    #     personal_tax = margin_personal_income_tax
    # else:
    #     personal_tax = total_personal_income_tax

    personal_tax = total_personal_income_tax

    seller_total = personal_tax + total_vat
    buyer_total = total_deed_tax

    print income_tax
    print total_personal_income_tax
    print margin_personal_income_tax
    print total_vat
    print total_deed_tax

    all_tax = seller_total + buyer_total



    return render_template('tax/tax_result.html', total_vat=total_vat, total_deed_tax=total_deed_tax,
                           seller_total=seller_total, buyer_total=buyer_total, all_tax=all_tax, personal_tax=personal_tax)


#个人所得税

app/templates/tax/combination_loan.html
{% extends 'tax/base.html' %}

{% block content %}


  <div class="weui-tab">

   <div class="weui-tab__bd">
    <div class="weui-navbar">
     <a class="weui-navbar__item" href="{{ url_for('tax.commercial_loan') }}"> 商业贷款 </a>
     <a class="weui-navbar__item" href="{{ url_for('tax.provident_fund_loan') }}"> 公积金贷款 </a>
     <a class="weui-navbar__item weui-bar__item--on" href="{{ url_for('tax.combination_loan') }}"> 组合贷款 </a>
    </div>
    <div class="weui-tab__bd">
     <div id="tab1" class="weui-tab__bd-item weui-tab__bd-item--active">
      <h1>页面一</h1>
     </div>


   </div>

   <div class="weui-tabbar">
    <a href="{{ url_for('tax.commercial_loan') }}" class="weui-tabbar__item weui-bar__item--on">
     <div class="weui-tabbar__icon">
      <img src="{{ url_for('static', filename='images/icon_nav_button.png') }}" alt="" />
     </div> <p class="weui-tabbar__label">房贷</p> </a>
    <a href="{{ url_for('tax.tax') }}" class="weui-tabbar__item">
     <div class="weui-tabbar__icon">
      <img src="{{ url_for('static', filename='images/icon_nav_article.png') }}" alt="" />
     </div> <p class="weui-tabbar__label">税费</p> </a>
    <a href="{{ url_for('tax.purchase') }}" class="weui-tabbar__item">
     <div class="weui-tabbar__icon">
      <img src="{{ url_for('static', filename='images/icon_nav_msg.png') }}" alt="" />
     </div> <p class="weui-tabbar__label">限购</p> </a>
    <a href="{{ url_for('tax.test4') }}" class="weui-tabbar__item">
     <div class="weui-tabbar__icon">
      <img src="{{ url_for('static', filename='images/icon_nav_cell.png') }}" alt="" />
     </div> <p class="weui-tabbar__label">预留</p> </a>
   </div>
  </div>

    </div>
{% endblock %}

app/templates/tax/commercial_loan.html
{% extends 'tax/base.html' %}

{% block content %}


<div class="weui-tab">
    <div class="weui-tab__bd">
        <div class="weui-navbar">
            <a class="weui-navbar__item weui-bar__item--on" href="{{ url_for('tax.commercial_loan') }}">商业贷款</a>
            <a class="weui-navbar__item" href="{{ url_for('tax.provident_fund_loan') }}">公积金贷款</a>
            <a class="weui-navbar__item" href="{{ url_for('tax.combination_loan') }}">组合贷款</a>
        </div>

        <div class="weui-tab__bd">
            <form action="{{ url_for('tax.commercial_calc') }}" method="POST">
                <div class="weui-cell">
                    <div class="weui-cell__hd">
                        <label class="weui-label">贷款总额(万)</label>
                    </div>
                    <div class="weui-cell__bd">
                        <input class="weui-input" name="loan_total" type="number" step="0.01" style="text-align:right" placeholder="请输入贷款总额 (万元)" required="" />
                    </div>
                </div>
                <div class="weui-cells" style="margin-top: 0">
                    <div class="weui-cell weui-cell_select weui-cell_select-after">
                        <div class="weui-cell__hd">
                            <label for="" class="weui-label">贷款年限</label>
                        </div>
                        <div class="weui-cell__bd">
                            <select class="weui-select" name="loan_year" style="direction: rtl">
                                <option value="30">30年</option>
                                <option value="29">29年</option>
                                <option value="28">28年</option>
                                <option value="27">27年</option>
                                <option value="26">26年</option>
                                <option value="25">25年</option>
                                <option value="24">24年</option>
                                <option value="23">23年</option>
                                <option value="22">22年</option>
                                <option value="21">21年</option>
                                <option value="20">20年</option>
                                <option value="19">19年</option>
                                <option value="18">18年</option>
                                <option value="17">17年</option>
                                <option value="16">16年</option>
                                <option value="15">15年</option>
                                <option value="14">14年</option>
                                <option value="13">13年</option>
                                <option value="12">12年</option>
                                <option value="11">11年</option>
                                <option value="10">10年</option>
                                <option value="9">9年</option>
                                <option value="8">8年</option>
                                <option value="7">7年</option>
                                <option value="6">6年</option>
                                <option value="5">5年</option>
                                <option value="4">4年</option>
                                <option value="3">3年</option>
                                <option value="2">2年</option>
                                <option value="1">1年</option>
                            </select>
                        </div>
                    </div>

                    <div class="weui-cell weui-cell_select weui-cell_select-after">
                        <div class="weui-cell__hd">
                            <label for="" class="weui-label">贷款利率</label>
                        </div>
                        <div class="weui-cell__bd">
                            <select class="weui-select" name="loan_rate" style="direction: rtl">
                                <option value="4.9">最新基准利率 | 4.9%</option>
                                <option value="3.43">7折利率 | 3.43%</option>
                                <option value="3.92">8折利率 | 3.92%</option>
                                <option value="4.067">8.3折利率| 4 .067%</option>
                                <option value="4.165">8.5折利率| 4 .165%</option>
                                <option value="4.312">8.8折利率| 4 .312%</option>
                                <option value="4.41">9折利率 | 4.41%</option>
                                <option value="4.655">9.5折利率| 4 .655%</option>
                                <option value="5.39">1.1倍利率 | 5.39%</option>
                                <option value="5.88">1.2倍利率 | 5.88%</option>
                                <option value="6.37">1.3倍利率 | 6.37%</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="demos-content-padded" style="padding-bottom: 60px;">
                    <button class="weui-btn weui-btn_primary" type="submit">开始计算</button>
                </div>
            </form>
        </div>

        <div class="weui-tabbar">
            <a href="{{ url_for('tax.commercial_loan') }}" class="weui-tabbar__item weui-bar__item--on">
                <div class="weui-tabbar__icon">
                    <img src="{{ url_for('static', filename='images/icon_nav_button.png') }}" alt="" />
                </div>
                <p class="weui-tabbar__label">房贷</p>
            </a>
            <a href="{{ url_for('tax.tax') }}" class="weui-tabbar__item">
                <div class="weui-tabbar__icon">
                    <img src="{{ url_for('static', filename='images/icon_nav_article.png') }}" alt="" />
                </div>
                <p class="weui-tabbar__label">税费</p>
            </a>
            <a href="{{ url_for('tax.purchase') }}" class="weui-tabbar__item">
                <div class="weui-tabbar__icon">
                    <img src="{{ url_for('static', filename='images/icon_nav_msg.png') }}" alt="" />
                </div>
                <p class="weui-tabbar__label">限购</p>
            </a>
            <a href="{{ url_for('tax.test4') }}" class="weui-tabbar__item">
                <div class="weui-tabbar__icon">
                    <img src="{{ url_for('static', filename='images/icon_nav_cell.png') }}" alt="" />
                </div>
                <p class="weui-tabbar__label">预留</p>
            </a>
        </div>

    </div>
</div>
{% endblock %}

app/templates/tax/provident_fund_loan.html
{% extends 'tax/base.html' %}

{% block content %}


  <div class="weui-tab">

   <div class="weui-tab__bd">
    <div class="weui-navbar">
     <a class="weui-navbar__item" href="{{ url_for('tax.commercial_loan') }}"> 商业贷款 </a>
     <a class="weui-navbar__item weui-bar__item--on" href="{{ url_for('tax.provident_fund_loan') }}"> 公积金贷款 </a>
     <a class="weui-navbar__item" href="{{ url_for('tax.combination_loan') }}"> 组合贷款 </a>
    </div>
    <div class="weui-tab__bd">
     <div id="tab1" class="weui-tab__bd-item weui-tab__bd-item--active">
      <h1>页面一</h1>
     </div>


   </div>

   <div class="weui-tabbar">
    <a href="{{ url_for('tax.commercial_loan') }}" class="weui-tabbar__item weui-bar__item--on">
     <div class="weui-tabbar__icon">
      <img src="{{ url_for('static', filename='images/icon_nav_button.png') }}" alt="" />
     </div> <p class="weui-tabbar__label">房贷</p> </a>
    <a href="{{ url_for('tax.tax') }}" class="weui-tabbar__item">
     <div class="weui-tabbar__icon">
      <img src="{{ url_for('static', filename='images/icon_nav_article.png') }}" alt="" />
     </div> <p class="weui-tabbar__label">税费</p> </a>
    <a href="{{ url_for('tax.purchase') }}" class="weui-tabbar__item">
     <div class="weui-tabbar__icon">
      <img src="{{ url_for('static', filename='images/icon_nav_msg.png') }}" alt="" />
     </div> <p class="weui-tabbar__label">限购</p> </a>
    <a href="{{ url_for('tax.test4') }}" class="weui-tabbar__item">
     <div class="weui-tabbar__icon">
      <img src="{{ url_for('static', filename='images/icon_nav_cell.png') }}" alt="" />
     </div> <p class="weui-tabbar__label">预留</p> </a>
   </div>
  </div>

{% endblock %}

app/templates/tax/tax.html
{% extends 'tax/base.html' %}

{% block content %}



<header>
    <h1 class="demos-title" style="font-size: 20px">上海二手房税费计算</h1>
</header>
<div class="weui-tab">
    <div class="weui-tab__bd" style="padding-bottom: 55px">
        <form action="{{ url_for('tax.tax_cal') }}" method="POST">
            <div class="weui-cell">
                <div class="weui-cell__hd">
                    <label class="weui-label">房屋位置</label>
                </div>
            </div>
            <div class="weui-cell">
                <div class="weui-cell__hd" style="width: 100%">
                    <div class="weui-flex" style="height: 39px">
                        <div class="weui-flex__item">
                            <div class="placeholder">
                                <li style="display: inline-block; text-align: center; width: 100%">
                                    <input type="radio" name="house_location" value="0" checked="" data-labelauty="内环以内" />
                                </li>
                            </div>
                        </div>
                        <div class="weui-flex__item">
                            <div class="placeholder">
                                <li style="display: inline-block; text-align: center; width: 100%">
                                    <input type="radio" name="house_location" value="1" data-labelauty="内外环间" />
                                </li>
                            </div>
                        </div>
                        <div class="weui-flex__item">
                            <div class="placeholder">
                                <li style="display: inline-block; text-align: center; width: 100%">
                                    <input type="radio" name="house_location" value="2" data-labelauty="外环以外" />
                                </li>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="weui-cell">
                <div class="weui-cell__hd">
                    <label class="weui-label">买入时间</label>
                </div>
            </div>
            <div class="weui-cell">
                <div class="weui-cell__hd" style="width: 100%">
                    <div class="weui-flex" style="height: 39px">
                        <div class="weui-flex__item">
                            <div class="placeholder">
                                <li style="display: inline-block; text-align: center; width: 100%">
                                    <input type="radio" name="house_year" value="5" checked="" data-labelauty="满5" />
                                </li>
                            </div>
                        </div>
                        <div class="weui-flex__item">
                            <div class="placeholder">
                                <li style="display: inline-block; text-align: center; width: 100%">
                                    <input type="radio" name="house_year" value="2" data-labelauty="满2" />
                                </li>
                            </div>
                        </div>
                        <div class="weui-flex__item">
                            <div class="placeholder">
                                <li style="display: inline-block; text-align: center; width: 100%">
                                    <input type="radio" name="house_year" value="0" data-labelauty="不满2" />
                                </li>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="weui-cell">
                <div class="weui-cell__hd">
                    <label class="weui-label">房屋总价(万)</label>
                </div>
                <div class="weui-cell__bd">
                    <input class="weui-input" name="house_total" type="number" step="0.01" style="text-align:right" placeholder="请输入房屋总价 (万元)" required="" />
                </div>
            </div>
            <div class="weui-cell">
                <div class="weui-cell__hd">
                    <label class="weui-label">买入价格(万)</label>
                </div>
                <div class="weui-cell__bd">
                    <input class="weui-input" name="house_org" type="number" step="0.01" style="text-align:right" placeholder="请输入买入价格 (万元)" required="" />
                </div>
            </div>
            <div class="weui-cell">
                <div class="weui-cell__hd">
                    <label class="weui-label">房屋面积(m&sup2;)</label>
                </div>
                <div class="weui-cell__bd">
                    <input class="weui-input" name="house_area" type="number" step="0.01" style="text-align:right" placeholder="请输入房屋面积 (m&sup2;)" required="" />
                </div>
            </div>
            <div class="weui-cell weui-cell_switch">
                <div class="weui-cell__bd">买方名下无房</div>
                <div class="weui-cell__ft">
                    <input class="weui-switch" name="buyerfirsthouse" data-switch="1" type="checkbox" checked="checked" />
                </div>
            </div>
            <div class="weui-cell weui-cell_switch">
                <div class="weui-cell__bd">卖方唯一住房</div>
                <div class="weui-cell__ft">
                    <input class="weui-switch" name="selleronlyhouse" data-switch="2" type="checkbox" checked="checked" />
                </div>
            </div>
            <div class="demos-content-padded" style="padding-bottom: 20px;">
                <button class="weui-btn weui-btn_primary" type="submit">开始计算</button>
            </div>
        </form>
        <div class="weui-footer">
            <p class="weui-footer__text">Copyright &copy; 2014-2017, pingmi.net, All Rights Reserved</p>
        </div>
    </div>
    <div class="weui-tabbar" style="position: fixed">
        <a href="{{ url_for('tax.commercial_loan') }}" class="weui-tabbar__item">
            <div class="weui-tabbar__icon">
                <img src="{{ url_for('static', filename='images/icon_nav_button.png') }}" alt="" />
            </div>
            <p class="weui-tabbar__label">房贷</p>
        </a>
        <a href="{{ url_for('tax.tax') }}" class="weui-tabbar__item  weui-bar__item--on">
            <div class="weui-tabbar__icon">
                <img src="{{ url_for('static', filename='images/icon_nav_article.png') }}" alt="" />
            </div>
            <p class="weui-tabbar__label">税费</p>
        </a>
        <a href="{{ url_for('tax.purchase') }}" class="weui-tabbar__item">
            <div class="weui-tabbar__icon">
                <img src="{{ url_for('static', filename='images/icon_nav_msg.png') }}" alt="" />
            </div>
            <p class="weui-tabbar__label">限购</p>
        </a>
        <a href="{{ url_for('tax.test4') }}" class="weui-tabbar__item">
            <div class="weui-tabbar__icon">
                <img src="{{ url_for('static', filename='images/icon_nav_cell.png') }}" alt="" />
            </div>
            <p class="weui-tabbar__label">预留</p>
        </a>
    </div>
</div>

{% endblock %}



{% block script %}

<script>

$(function(){
	$(':radio').labelauty();
});

</script>

{% endblock %}

app/templates/tax/test4.html
{% extends 'tax/base.html' %}

{% block content %}
    <div class="weui-tab">



      <div class="weui-tab__bd">
        <h1>页面4</h1>
      </div>







      <div class="weui-tabbar">

        <a href="{{ url_for('tax.combination_loan') }}" class="weui-tabbar__item">
          <div class="weui-tabbar__icon">
            <img src="{{ url_for('static', filename='images/icon_nav_button.png') }}" alt="">
          </div>
          <p class="weui-tabbar__label">房贷</p>
        </a>

        <a href="{{ url_for('tax.tax') }}" class="weui-tabbar__item">
          <div class="weui-tabbar__icon">
            <img src="{{ url_for('static', filename='images/icon_nav_article.png') }}" alt="">
          </div>
          <p class="weui-tabbar__label">税费</p>
        </a>

        <a href="{{ url_for('tax.purchase') }}" class="weui-tabbar__item">
          <div class="weui-tabbar__icon">
            <img src="{{ url_for('static', filename='images/icon_nav_msg.png') }}" alt="">
          </div>
          <p class="weui-tabbar__label">限购</p>
        </a>

        <a href="{{ url_for('tax.test4') }}" class="weui-tabbar__item weui-bar__item--on">
          <div class="weui-tabbar__icon">
            <img src="{{ url_for('static', filename='images/icon_nav_cell.png') }}" alt="">
          </div>
          <p class="weui-tabbar__label">预留</p>
        </a>

      </div>
    </div>

{% endblock %}